### ISSUE TITLE
网易原版的侧滑菜单跳转是怎么做的？

### ISSUE THREAD

**Issue by txxxtxx** [limiaomaster/NetEaseMusic#1]
网易原版的侧滑菜单跳转的界面好像有很多种方式，因为不知道代码，仅仅从效果上面看，有的是启动新的activity，有的是切换fragment，这种应该怎么弄？

**Comment by limiaomaster** [comment]
您说的是哪种？这个仓库我没更新过，你可以看我MyMusicPlayer这个仓库，大体上做了不少了呢。

**Comment by txxxtxx** [comment]
好的  我去看看

**Comment by limiaomaster** [comment]
恩恩，那个才是我一直在做的呢。谢谢关注。
